version: '3'
services:
  crossbar:
    image: 'crossbario/crossbar:latest'
  eventstore:
    image: 'eventstore/eventstore:latest'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - '8000:8000'
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
