version: '3'
services:
  eventstore:
    image: 'eventstore/eventstore:release-3.7.0'
    ports:
      - '1113:1113'
      - '2113:2113'
  broker:
    image: 'crossbario/crossbar:community'
    ports:
      - '8000:8000'
    volumes:
      - ./server/.crossbar:/node/.crossbar
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
  analytics:
    build:
      dockerfile: Dockerfile
      context: ./server
    command: 'dotnet run --configuration Release -p Adaptive.ReactiveTrader.Server.Analytics config.prod.json'
    depends_on:
      - broker
      - eventstore
  pricing:
    build:
      dockerfile: Dockerfile
      context: ./server
    command:
      [
        sh,
        -c,
        'dotnet run -p Adaptive.ReactiveTrader.Server.Launcher --populate-eventstore && dotnet run --configuration Release -p Adaptive.ReactiveTrader.Server.Pricing config.prod.json',
      ]
    depends_on:
      - broker
      - eventstore
      - analytics
  referencedataread:
    build:
      dockerfile: Dockerfile
      context: ./server
    command: 'dotnet run --configuration Release -p Adaptive.ReactiveTrader.Server.ReferenceDataRead config.prod.json'
    depends_on:
      - broker
      - eventstore
      - pricing
  tradeexecution:
    build:
      dockerfile: Dockerfile
      context: ./server
    command: 'dotnet run --configuration Release -p Adaptive.ReactiveTrader.Server.TradeExecution config.prod.json'
    depends_on:
      - broker
      - eventstore
      - referencedataread
  blotter:
    build:
      dockerfile: Dockerfile
      context: ./server
    command: 'dotnet run --configuration Release -p Adaptive.ReactiveTrader.Server.Blotter config.prod.json'
    depends_on:
      - broker
      - eventstore
      - tradeexecution
