version: '3'
services:
  eventstore:
    image: 'eventstore/eventstore:release-3.7.0'
    ports:
      - '1113:1113'
      - '2113:2113'
  broker:
    image: 'crossbario/crossbar:community'
    ports:
      - '8000:8000'
    volumes:
      - ./server/.crossbar:/node/.crossbar
  servers:
    build:
      dockerfile: Dockerfile
      context: ./server
  #Stuck on event store population, check deploy scripts
  #client:
  #  build:
  #    dockerfile: Dockerfile.dev
  #    context: ./client
  #  volumes:
  #    - /app/node_modules
  #    - ./client:/app
  #  ports:
  #    - '3000:3000'
